# Generated by Django 4.2.1 on 2023-05-14 17:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_pressure_temperature_delete_sensordata'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pressure',
            name='user',
        ),
        migrations.RemoveField(
            model_name='temperature',
            name='user',
        ),
    ]
